const app=document.querySelector('#onlineApp');
const atlas=['exec-7264418b-bbb9-4f93-aade-3cbdadc27595.png','exec-f436e953-9fee-4356-acf1-9d63ae294270.png','exec-7154a9e1-6b60-46f0-ab36-97b7d2bed74c.png','exec-386f48ed-4f0c-4bf1-91b5-1e3e2d9fa75a.png'];
const data=[
['bufalo','Búfalo de Acero','Tanque','Guardián',3],['conejo','Conejo Relámpago','Ágil','Ágil',1],['elefante','Elefante Guardián','Tanque','Guardián',3],['ciervo','Ciervo Centella','Ágil','Armonioso',1],['tortuga','Tortuga Férrea','Tanque','Guardián',3],['hipopotamo','Hipopótamo Barrera','Tanque','Territorial',3],['carnero','Carnero Rocoso','Daño','Territorial',2],['jirafa','Jirafa Vigía','Soporte','Armonioso',1],['jabali','Jabalí Salvaje','Daño','Adaptable',2],['camello','Camello del Desierto','Soporte','Armonioso',1],['koala','Koala Tenaz','Soporte','Armonioso',1],['caballo','Caballo del Alba','Ágil','Ágil',1],['lobo','Lobo del Trueno','Daño','Cazador',2],['tigre','Tigre Fantasma','Daño','Emboscador',2],['zorro','Zorro Carmesí','Ágil','Ágil',1],['leopardo','Leopardo Sombrío','Daño','Emboscador',2],['mapache','Mapache Acechador','Soporte','Adaptable',1],['cocodrilo','Cocodrilo Emboscador','Tanque','Territorial',3],['aguila','Águila del Horizonte','Ágil','Cazador',1],['escorpion','Escorpión Letal','Daño','Emboscador',2],['nutria','Nutria Depredadora','Soporte','Adaptable',1],['murcielago','Murciélago Nocturno','Soporte','Emboscador',1],['oso','Oso de Montaña','Tanque','Territorial',3],['serpiente','Serpiente de Sombra','Ágil','Emboscador',1],['tiburon','Tiburón de Mareas','Daño','Cazador',2],['delfin','Delfín Guardián','Soporte','Guardián',1],['pulpo','Pulpo del Abismo','Soporte','Emboscador',1],['pirana','Piraña Escarlata','Ágil','Cazador',1],['castor','Castor Constructor','Tanque','Guardián',3],['capibara','Capibara Serena','Soporte','Armonioso',1],['puercoespin','Puercoespín Espinoso','Tanque','Guardián',3],['ardilla','Ardilla Veloz','Ágil','Ágil',1],['buho','Búho Vigilante','Soporte','Cazador',1],['halcon','Halcón Solar','Daño','Cazador',2],['pantera','Pantera Lunar','Daño','Emboscador',2],['rinoceronte','Rinoceronte Territorial','Tanque','Territorial',3]
].map((x,i)=>({id:x[0],name:x[1],role:x[2],instinct:x[3],lives:x[4],index:i}));
let socket,currentRoom,you,selected=[],filter='Todos',confirmed=[],countdownTimer,lastChoice,lastBattle,battleTimer;
const unit=id=>data.find(x=>x.id===id);
function shell(content,narrow=false){app.innerHTML=`<div class="online-shell"><section class="online-panel ${narrow?'narrow':''}">${content}</section></div>`}
function portrait(u){let cell=u.index%9,col=cell%3,row=Math.floor(cell/3);return`<div class="portrait" style="background-image:url('${atlas[Math.floor(u.index/9)]}');background-position:${col*50}% ${row*50}%"></div>`}
function lobby(message=''){shell(`<h1>COLMILLOS <span>VS. CUERNOS</span></h1><p class="tagline">MULTIJUGADOR EN LÍNEA</p>${message?`<p class="status error">${message}</p>`:''}<div class="online-form"><input id="playerName" maxlength="18" placeholder="TU NOMBRE"><button onclick="createRoom()">CREAR SALA</button><div class="divider">O</div><input id="roomCode" maxlength="5" placeholder="CÓDIGO DE SALA"><button class="secondary" onclick="joinRoom()">UNIRME A UNA SALA</button></div>`,true)}
function connect(action){if(socket&&socket.readyState===1)return action();let protocol=location.protocol==='https:'?'wss:':'ws:';socket=new WebSocket(`${protocol}//${location.host}`);socket.addEventListener('open',action,{once:true});socket.addEventListener('message',receive);socket.addEventListener('close',()=>currentRoom&&lobby('Se perdió la conexión.'));socket.addEventListener('error',()=>lobby('No fue posible conectar.'))}
function createRoom(){let name=document.querySelector('#playerName').value.trim()||'Jugador 1';connect(()=>socket.send(JSON.stringify({type:'create_room',name})))}
function joinRoom(){let name=document.querySelector('#playerName').value.trim()||'Jugador 2',code=document.querySelector('#roomCode').value.trim().toUpperCase();if(code.length!==5)return lobby('Escribe el código de cinco caracteres.');connect(()=>socket.send(JSON.stringify({type:'join_room',name,code})))}
function receive(event){let d=JSON.parse(event.data);if(d.type==='error')return lobby(d.message);if(d.you)you=d.you;if(['room_created','room_joined','room_state'].includes(d.type)){currentRoom=d;return showRoom(d)}if(d.type==='team_status'){confirmed=d.confirmed;return confirmed.includes(you)?waitingTeams():showBuilder()}if(d.type==='teams_locked')return showLocked(d.teams);if(d.type==='choose_combatant')return showCombatantChoice(d);if(d.type==='pick_saved')return showPickWaiting();if(d.type==='battle_result')return showOnlineBattle(d);if(d.type==='rematch_status')return showRematchWaiting(d.votes);if(d.type==='new_team_selection'){selected=[];confirmed=[];filter='Todos';return showBuilder()}}
function showRoom(room){currentRoom={...currentRoom,...room};let seats=[1,2].map(n=>{let p=room.players.find(x=>x.number===n);return`<div class="player-seat ${p?'':'empty'}"><b>JUGADOR ${n}${n===you?' · TÚ':''}</b><h2>${p?p.name:'Esperando…'}</h2></div>`}).join('');shell(`<h2>SALA PRIVADA</h2><p>Código para tu amigo:</p><div class="room-code">${room.code}</div><div class="players">${seats}</div><p class="status ${room.ready?'':'pulse'}">${room.ready?'✓ Ambos conectados. Ya pueden formar sus equipos.':'Esperando al segundo jugador…'}</p>${room.ready?'<button class="online-button" onclick="showBuilder()">FORMAR MI EQUIPO</button>':`<button class="online-button" onclick="copyCode('${room.code}')">COPIAR CÓDIGO</button>`}`,true)}
function showBuilder(){let shown=filter==='Todos'?data:data.filter(u=>u.role===filter),rival=you===1?2:1,rivalReady=confirmed.includes(rival);shell(`<h2>JUGADOR ${you} · FORMA TU EQUIPO</h2><p>Tu rival no verá tus elecciones hasta que ambos confirmen.</p>${rivalReady?'<p class="status ready-mark">✓ Tu rival ya confirmó. Puedes terminar tu selección con tranquilidad.</p>':''}<div class="team-slots">${Array.from({length:6},(_,i)=>{let u=unit(selected[i]);return u?`<div class="team-slot filled">${portrait(u)}<div class="slot-label">${u.name}</div></div>`:`<div class="team-slot">ESPACIO ${i+1}</div>`}).join('')}</div><nav class="filters">${['Todos','Daño','Tanque','Ágil','Soporte'].map(r=>`<button class="filter ${filter===r?'active':''}" onclick="setFilter('${r}')">${r}</button>`).join('')}</nav><div class="animal-grid">${shown.map(u=>{let order=selected.indexOf(u.id);return`<button class="animal ${order>=0?'selected':''}" onclick="toggle('${u.id}')">${order>=0?`<span class="number">${order+1}</span>`:''}${portrait(u)}<h3>${u.name}</h3><p>${u.role} · ${u.instinct}</p><p>Vidas: ${u.lives}</p></button>`}).join('')}</div><div class="sticky-actions"><b>${selected.length}/6</b><button class="online-button" ${selected.length!==6?'disabled':''} onclick="confirmTeam()">CONFIRMAR EQUIPO</button></div>`)}
function setFilter(value){filter=value;showBuilder()}function toggle(id){let i=selected.indexOf(id);if(i>=0)selected.splice(i,1);else if(selected.length<6)selected.push(id);showBuilder()}
function confirmTeam(){if(selected.length!==6)return;socket.send(JSON.stringify({type:'select_team',team:selected}));confirmed=[you];waitingTeams()}
function waitingTeams(){let rival=you===1?2:1,sent=confirmed.includes(you),other=confirmed.includes(rival);shell(`<h2>EQUIPO CONFIRMADO</h2><div class="waiting-mark ${sent?'ready-mark':''}">${sent?'✓':'…'}</div><p class="status">Tu equipo está guardado de forma segura.</p><div class="players"><div class="player-seat"><b>JUGADOR ${you} · TÚ</b><h2>${sent?'LISTO':'SELECCIONANDO'}</h2></div><div class="player-seat"><b>JUGADOR ${rival}</b><h2>${other?'LISTO':'SELECCIONANDO…'}</h2></div></div><p>La guerra comenzará cuando ambos equipos estén listos.</p>`,true)}
function showLocked(teams){shell(`<h2>AMBOS EQUIPOS ESTÁN LISTOS</h2><p class="status ready-mark">✓ Formación sincronizada correctamente</p><div class="locked-teams">${[1,2].map(n=>`<section class="locked-team"><h3>JUGADOR ${n}${n===you?' · TÚ':''}</h3><div class="locked-list">${teams[n].map(id=>{let u=unit(id);return`<div class="locked-unit">${portrait(u)}<b>${u.name}</b><p>${u.role} · ${u.lives} vidas</p></div>`}).join('')}</div></section>`).join('')}</div><p>Próxima etapa: elección secreta del primer combatiente y batalla sincronizada.</p>`)}
function stateUnit(state,n,id){return state.units[n].find(u=>u.id===id)}
function unitMini(state,n,id,active=false){let base=unit(id),u=stateUnit(state,n,id);return`<div class="combat-mini ${u.eliminated?'eliminated':''} ${active?'active':''}">${portrait(base)}<b>${base.name}</b><span>❤️ ${u.livesLeft}/${u.lives} · ⭐ ${u.level}</span></div>`}
function showCombatantChoice(state){clearInterval(countdownTimer);lastChoice=state;let mine=state.units[you],rival=you===1?2:1;function draw(){let seconds=Math.max(0,Math.ceil((state.deadline-Date.now())/1000));shell(`<h2>RONDA ${state.round} · ELECCIÓN SECRETA</h2><div class="choice-clock">${seconds}</div><p>Escoge tu combatiente. El rival no verá tu elección hasta que ambos hayan decidido.</p><div class="combat-choice-layout"><section><h3>MI EQUIPO</h3><div class="combat-roster">${mine.map(u=>`<button class="combat-pick ${u.eliminated?'eliminated':''}" ${u.eliminated?'disabled':''} onclick="pickCombatant('${u.id}')">${portrait(unit(u.id))}<b>${unit(u.id).name}</b><span>${u.livesLeft} vidas · Nivel ${u.level}</span></button>`).join('')}</div></section><section><h3>EQUIPO RIVAL</h3><div class="combat-roster">${state.units[rival].map(u=>unitMini(state,rival,u.id)).join('')}</div></section></div>`);if(seconds<=0)clearInterval(countdownTimer)}draw();countdownTimer=setInterval(draw,1000)}
function pickCombatant(id){clearInterval(countdownTimer);socket.send(JSON.stringify({type:'pick_combatant',id}));showPickWaiting()}
function showPickWaiting(){shell(`<h2>ELECCIÓN GUARDADA</h2><div class="waiting-mark ready-mark">✓</div><p class="status">Tu animal permanece oculto.</p><p class="pulse">Esperando la elección del rival…</p>`,true)}
function showOnlineBattle(result){clearInterval(countdownTimer);clearTimeout(battleTimer);lastBattle=result;playBattleStep(0)}
function playBattleStep(step){clearTimeout(battleTimer);let r=lastBattle,a=unit(r.chosen[1]),b=unit(r.chosen[2]),hp={1:r.maxHp[1],2:r.maxHp[2]},sideByUnit={[r.chosen[1]]:1,[r.chosen[2]]:2},shown=r.log.slice(0,step);shown.forEach(x=>{let side=sideByUnit[x.defender];if(side)hp[side]=Math.max(0,Number(x.hp))});let current=r.log[step-1],finished=step>=r.log.length,winner=unit(r.chosen[r.winner]);shell(`<h2>RONDA ${r.round} · SABANA DORADA</h2><div class="online-arena"><article class="${current&&current.defender===a.id?'battle-hit':''}">${portrait(a)}<h3>${a.name}</h3><div class="life-bar" role="progressbar" aria-label="Vida de ${a.name}" aria-valuemin="0" aria-valuemax="${r.maxHp[1]}" aria-valuenow="${hp[1]}"><i style="width:${Math.max(0,Math.min(100,hp[1]/r.maxHp[1]*100))}%"></i></div><b>Jugador 1 · ${Math.round(hp[1])}/${r.maxHp[1]}</b></article><div class="online-vs">VS</div><article class="${current&&current.defender===b.id?'battle-hit':''}">${portrait(b)}<h3>${b.name}</h3><div class="life-bar" role="progressbar" aria-label="Vida de ${b.name}" aria-valuemin="0" aria-valuemax="${r.maxHp[2]}" aria-valuenow="${hp[2]}"><i style="width:${Math.max(0,Math.min(100,hp[2]/r.maxHp[2]*100))}%"></i></div><b>Jugador 2 · ${Math.round(hp[2])}/${r.maxHp[2]}</b></article>${current?`<span class="floating-damage ${current.critical?'critical':''}">-${current.damage}</span>`:''}</div><div class="online-log">${shown.slice(-14).map(x=>`<p>${x.critical?'💥':'⚔️'} ${unit(x.attacker).name} causó <b>${x.damage}</b> a ${unit(x.defender).name}.</p>`).join('')||'<p>Los combatientes se preparan…</p>'}</div>${finished?battleEndControls(r,winner):`<button class="online-button secondary" onclick="playBattleStep(${r.log.length})">SALTAR AL RESULTADO</button>`}`);if(!finished)battleTimer=setTimeout(()=>playBattleStep(step+1),650)}
function battleEndControls(r,winner){return`<h2 class="battle-winner">${winner.name} ganó la batalla</h2>${r.warOver?`<div class="war-victory">🏆 JUGADOR ${r.winner} GANÓ LA GUERRA</div><div class="end-actions"><button class="online-button secondary" onclick="playBattleStep(0)">REPETIR ÚLTIMA BATALLA</button><button class="online-button" onclick="voteRematch('same')">REVANCHA · MISMOS EQUIPOS</button><button class="online-button" onclick="voteRematch('new')">ESCOGER NUEVOS EQUIPOS</button></div>`:`<div class="end-actions"><button class="online-button secondary" onclick="playBattleStep(0)">REPETIR BATALLA</button><button class="online-button" onclick="continueBattle()">SIGUIENTE ELECCIÓN</button></div>`}`}
function voteRematch(mode){socket.send(JSON.stringify({type:'rematch_vote',mode}));showRematchWaiting([you])}function showRematchWaiting(votes){shell(`<h2>DECISIÓN GUARDADA</h2><div class="waiting-mark ready-mark">✓</div><p class="status">${votes.length}/2 jugadores listos</p><p class="pulse">Esperando la decisión del rival…</p>`,true)}
function continueBattle(){socket.send(JSON.stringify({type:'battle_continue'}));shell(`<h2>LISTO PARA CONTINUAR</h2><p class="pulse">Esperando al rival…</p>`,true)}
function copyCode(code){navigator.clipboard?.writeText(code)}lobby();
